name: Release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  Get_Version:
    if: github.event.pull_request.merged == true
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      run: |
        [[ tag=$(git descrite --tags --abbrev=0) || tag=$(git describe --abbrev=0) ]]
        echo $tag
