name: Release
on:
  pull_request_target:
    branches: [main]
    types: [closed]

jobs:
  semver:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        run: |
          [[ tag=$(git describe --tags --abbrev=0) || tag=$(git describe --abbrev=0) ]]
          echo "${tag}"
